name: flutter_app_std
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  line_icons: ^2.0.1
  flutter_bloc: ^9.1.1
  google_nav_bar: ^5.0.7
  bloc: ^9.0.0
  meta: ^1.15.0
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  supabase_flutter: ^2.9.1
  async: 2.12.0 # متوافق مع flutter_test
  fake_async: 1.3.2
  leak_tracker: 10.0.8
  leak_tracker_flutter_testing: 3.0.9
  leak_tracker_testing: 3.0.1
  lints: ^5.0.0
  material_color_utilities: 0.11.1
  vector_math: 2.1.4
  vm_service: 14.3.1
  google_sign_in: ^5.4.4
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/undraw_shopping-bags_nfsf.png
    - assets/images/image.png
    - assets/images/undraw_mobile-log-in_0n4q.png
